### ISSUE TITLE
giving karma to a nicks with _ does not parse correctly

### ISSUE THREAD

**Issue by ianthpun** [oldterns/VileBot#50] opened 2017-05-30 18:30 UTC
Example:

doing a omajid_wfh++ doesn't actually give omajid_wfh any karma, but gives it to omajid instead. This might be by design though.

EDIT: refer to @omajid 's comment. There seems to be a problem with karma not being given to anybody went set to a nick with _ in it

**Comment by emmettu** [comment] 2017-05-30 18:48
This is by design. https://github.com/oldterns/VileBot/blob/master/vilebot/src/com/oldterns/vilebot/util/BaseNick.java

**Comment by itpun** [comment] 2017-05-30 19:04
beacuse its by design, I'm going to close it.

**Comment by omajid** [comment] 2017-05-30 19:58
Um. Isnt the bug that its not giving karma to anyone?

**Comment by omajid** [comment] 2017-05-30 20:03
>     < user1> !rank omajid
>     < VileBot1> omajid is ranked at #9 with 155 points of karma.
>     < user1> !rank omajid_wfh 
>     < VileBot1> omajid_wfh has no karma.
>     < user1> omajid_wfh++
>     < user1> !rank omajid
>     < VileBot1> omajid is ranked at #9 with 155 points of karma.
>     < user1> !rank omajid_wfh 
>     < VileBot1> omajid_wfh has no karma.
>     < omajid_wfh> whaaaa
>     < user1> did I do something wrong?
>     < user1> or is there a regression in Vilebot1
>     < user1> omajid++
>     < user1> !rank omajid
>     < VileBot1> omajid is ranked at #9 with 156 points of karma.
>     <@user2> omajid_wfh++
>     <@user2> !rank omajid
>     < VileBot1> omajid is ranked at #9 with 156 points of karma.

**Comment by ASzc** [comment] 2017-05-30 20:10
BaseNick, as applied to noun karma, should redirect the karma to the simplified noun. So, `omajid_wfh has no karma.` would be expected, but it also should be incrementing `omajid` when receiving `omajid_wfh++`

**Comment by omajid** [comment] 2017-05-30 22:35
Sounds like you agree that the issue should be re-opened :)

**Comment by itpun** [comment] 2017-05-30 22:36
I agree, reopened.

**Closed** 2019-05-24 13:46 UTC
Labels: bug, good first issue, help wanted
