### ISSUE TITLE
VileBot doesn't use title for new members of the Church!

### ISSUE THREAD

**Issue by Christopher-Chianelli** [oldterns/VileBot#55] opened 2017-06-06 13:16 UTC
If a user become a top donor and replace an older top donor, their title does not appear upon logging in/quotes/etc..

**Comment by itpun** [comment] 2017-06-06 13:50
@yuqi-zhang ^

**Comment by csanting** [comment] 2017-06-27 14:55
Isn't that by design? if a new member joins they do not have a title until they set one

**Comment by Christopher-Chianelli** [comment] 2017-06-27 15:01
I mean after they do !setTitle, their title doesn't change

**Comment by onyiny-ang** [comment] 2018-07-10 23:41
@Christopher-Chianelli Only the top 4 members of the church get to set their titles. I don't really remember if there was a resolution to this or not.

**Comment by Christopher-Chianelli** [comment] 2018-07-23 15:58
@onyiny-ang  I think it is fixed; way back when I was a top doner and set my title, it didn't show my title in quotes/fact/when I log in, but it appears to be working for all current members of the church.

**Comment by onyiny-ang** [comment] 2018-07-23 16:10
@Christopher-Chianelli ok, I'm going to close this then :+1:

**Closed by onyiny-ang** 2018-07-23 16:10 UTC
